/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testApp() {
        String[] test = {"test"};
        App.main(test);
        assertNotNull("app should have a greeting", App.getMenu());
        assertNull("app should have a greeting", App.getScoreMenu());
    }
}

